/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janken.view;

import janken.controller.JankenHumanPlayerController;
import janken.model.JankenPlayer;

/**
 *
 * @author iijim
 */
public class JankenHumanPlayerControlPanel extends JankenPlayerControlPanel {

    /**
     * Creates new form JankenHumanPlayerControlPanel
     */
    public JankenHumanPlayerControlPanel(JankenPlayer player) {
        super(player);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guuButton = new javax.swing.JButton();
        chokiButton = new javax.swing.JButton();
        paaButton = new javax.swing.JButton();

        guuButton.setText("ぐー");
        guuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guuButtonActionPerformed(evt);
            }
        });

        chokiButton.setText("ちょき");
        chokiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chokiButtonActionPerformed(evt);
            }
        });

        paaButton.setText("ぱー");
        paaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(guuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chokiButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paaButton)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guuButton)
                    .addComponent(chokiButton)
                    .addComponent(paaButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guuButtonActionPerformed
        ((JankenHumanPlayerController)playerController).guu();
    }//GEN-LAST:event_guuButtonActionPerformed

    private void chokiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chokiButtonActionPerformed
        ((JankenHumanPlayerController)playerController).choki();
    }//GEN-LAST:event_chokiButtonActionPerformed

    private void paaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paaButtonActionPerformed
        ((JankenHumanPlayerController)playerController).paa();
    }//GEN-LAST:event_paaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chokiButton;
    private javax.swing.JButton guuButton;
    private javax.swing.JButton paaButton;
    // End of variables declaration//GEN-END:variables
}
