/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janken.view;

import janken.controller.JankenMatchController;
import janken.model.JankenMatch;

/**
 *
 * @author iijim
 */
public class JankenMatchControlPanel extends javax.swing.JPanel {
    private JankenMatch match = null;
    private JankenMatchController matchController = null;
    /**
     * Creates new form JankenMatchControlPanel
     */
    public JankenMatchControlPanel(JankenMatch match) {
        initComponents();
        this.match = match;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judgeButon = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        judgeButon.setText("判定");
        judgeButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judgeButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(judgeButon)
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(judgeButon)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void judgeButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judgeButonActionPerformed
        matchController.judge();
    }//GEN-LAST:event_judgeButonActionPerformed

    public void setController(JankenMatchController matchController) {
        this.matchController = matchController;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton judgeButon;
    // End of variables declaration//GEN-END:variables
}
