/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digital_clock.view;

import digital_clock.controller.DigitalClockController;
import digital_clock.model.DigitalClock;
import java.awt.BorderLayout;
import java.awt.FlowLayout;

/**
 * ディジタルクロック
 * @author 飯島 正(iijima@ae.keio.ac.jp)
 */
public class DigitalClockFrame extends javax.swing.JFrame {
    private DigitalClock clock = null;
    private DigitalClockView view = null;
    private DigitalClockControlPanel controlPanel = null;
    private DigitalClockController controller = null;
    /**
     * 
     */
    public DigitalClockFrame(DigitalClock clock) {
        initComponents();
        this.clock = clock;
        view = new DigitalClockView( clock );
        controlPanel = new DigitalClockControlPanel( clock );
        controller = new DigitalClockController( clock, view, controlPanel );
        controlPanel.setController(controller);
        
        setLayout( new BorderLayout());
        add( view, BorderLayout.CENTER );
        add( controlPanel, BorderLayout.SOUTH );
        
        pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        exitMenuItem.setText("終了");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        controller.exit();
    }//GEN-LAST:event_exitMenuItemActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
