/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janken.view;

import janken.controller.JankenMatchController;
import janken.model.JankenMatch;
import janken.model.JankenPlayer;
import java.awt.BorderLayout;

/**
 *
 * @author iijim
 */
public class JankenMatchFrame extends javax.swing.JFrame {

    private JankenMatch match = null;
    private JankenMatchView matchView = null;
    private JankenMatchControlPanel matchControlPanel = null;
    private JankenMatchController matchController = null;

    private JankenPlayer[] players = null;
    private JankenPlayerFrame[] playerFrames = null;

    /**
     * Creates new form JankenMatchFrame
     */
    public JankenMatchFrame(JankenMatch match) {
        initComponents();
        this.match = match;

        players = match.getPlayers();

        int x = getX();
        int y = getY();
        int w = getWidth();
        int h = getHeight();

        playerFrames = new JankenPlayerFrame[players.length];
        for (int i = 0; i < players.length; i++) {
            playerFrames[i] = new JankenPlayerFrame(players[i]);
            playerFrames[i].setTitle(players[i].getName());
            playerFrames[i].setLocation(x + (i * (playerFrames[i].getWidth())), y + h);
            playerFrames[i].setVisible(true);
        }

        matchView = new JankenMatchView(match);
        matchControlPanel = new JankenMatchControlPanel(match);
        matchController = new JankenMatchController(match, matchView, matchControlPanel);
        matchControlPanel.setController(matchController);

        setLayout(new BorderLayout());
        add( matchView, BorderLayout.CENTER);
        add( matchControlPanel, BorderLayout.SOUTH);
        pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
